### ISSUE TITLE
How to correctly simulate divio server live mode - including storage and DB simulation?

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#15]
The basic instruction is here - https://docs.divio.com/en/latest/how-to/local-in-live-mode/

But doesn't explain how to fetch DB url and storage DSN, which doesn't allow to simulate media errors, eg on azure integration.

**Comment by viktor-yunenko** [comment]
It's possible to ssh into the server and print the `env`s out.

**Comment by viktor-yunenko** [comment]
We should add it the documentation, https://docs.divio.com/en/latest/how-to/local-in-live-mode/

**Comment by evildmp** [comment]
@victor-yunenko https://docs.divio.com/en/latest/how-to/local-in-live-mode/#use-the-cloud-media-storage-rather-than-local-file-storage

**Comment by viktor-yunenko** [comment]
Thank you, that looks great, I can close this ticket now 👍
