### ISSUE TITLE
Control panel "Env Variables" section should contain all the utilized values, even the non-editable ones

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#17]
Eg otherwise it becomes confusing when somebody adds another storage DSN, developers start thinking that it is the divio DSN, as the DEFAULT_STORAGE_DSN isn't shown.

It would be better to show those values as `<input disabled>` elements:

![image](https://user-images.githubusercontent.com/36416236/86482251-432dc200-bd5a-11ea-8998-05fa6746dc62.png)

**Comment by macolo** [comment]
🎉  @kinkerl thank you 🙏 

all env vars are now visible (the ones that are set by the system are listed on top for every environment)
