### ISSUE TITLE
PHP project deployment fails on the migration step without a clear error

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#22]
This is a short log from the times when I tried to set the project up:

I created a new project, but it fails this time without an error:
```
===== docker build =====
starting docker build
```

I guess it was supposed to clone php boilerplate? I can see that the docker file is empty. It appears that on the project creation although laravel can be selected, it isn't possible to select it's boiprate (the option isn't there) - hence it's possible to create a project with empty codebase?

I quickly switched to symfony setup, but I can see that it tries to connect to mysql while divio configures a postgres service for it instead :)

**Comment by viktor-yunenko** [comment]
Yes, deleting the existing postgres service completely and creating a new one with `DEFAULT` prefix fixes the deployment

**Comment by kinkerl** [comment]
this was a configuration error. the boilerplate with the correct setup was not visible. fixed now!

**Comment by viktor-yunenko** [comment]
Sounds great, thank you! I can close this ticket now then  👍
