### ISSUE TITLE
SECURE_SSL_REDIRECT does not work for non-django project (react frontend app)

### ISSUE THREAD

**Issue by macolo** [what-digital/divio#24]
SECURE_SSL_REDIRECT to True on this react frontend (and deployed successfully) but the website is still available via HTTP: http://kendris-connect-frontend-stage.us.aldryn.io/login shouldnt there be a forced HTTPS redirect?

Docs: http://support.divio.com/en/articles/17824-essential-knowledge-ssl-certificates-and-https-on-divio-projects

**Comment by macolo** [comment]
> SECURE_SSL_REDIRECT only works in Django. It's handled by Aldryn Django, in fact.
> 
> Maybe https://docs.divio.com/en/latest/how-to/node-express-force-https/ is a helpful alternative, or at least a pointer to one

**Comment by macolo** [comment]
I am trying something like the below:

Dockerfile
```
FROM node:12.16.1 as builder

# for caching optimisations
COPY package*.json /
RUN npm install


COPY . /app
WORKDIR /app

# noop files for non python projects and local development
RUN echo "#!/bin/bash" > /app/migrate.sh && chmod +x /app/migrate.sh
RUN echo "#!/bin/bash" > /usr/local/bin/start && chmod +x /usr/local/bin/start

ENV PATH=/node_modules/.bin:$PATH

RUN npm run build


FROM nginx:latest
COPY --from=builder /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/default.conf /etc/nginx/conf.d

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]

```

nginx/default.conf
```
## Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;

    client_max_body_size 20M;

    if ($http_x_forwarded_proto != 'https') {
        return 301 https://$host$request_uri;
    }

    location / {
      alias /usr/share/nginx/html/;
      try_files $uri $uri/ /index.html =404;
    }

}

```

**Comment by macolo** [comment]
@GaretJax FYI - I am trying to solve this with nginx, but havent figured out yet how this behaves on Divio or how it behaves locally.

The idea is that we have wildcard support (all paths go to index.html so that React's routing can come into effect). I assume that HTTPS only goes to the load balancer, and behind the load balancer, the container handles all request on port 80.

If you can help with some pointers that would be much appreciated.

**Comment by GaretJax** [comment]
Correct, the LB terminates TLS, so all connections to the containers are HTTP.

What's wrong with the nginx snippet? It does not redirect? Our LB sets the x-forwarded-proto header accordingly, so it should work.

You could try logging the value to see if nginx handles it specially somehow. Instructions [here](https://docs.nginx.com/nginx/admin-guide/monitoring/logging/) if needed.

(as an aside listening on IPv6 is not required, as we don't support it at the LB level)

**Comment by macolo** [comment]
> What's wrong with the nginx snippet? 

the problem here is that local dev env doesnt work like this. in the local docker-compose.yml the CMD is overridden by a "yarn start" or similar.

do you have a sample Dockerfile for static file serving with nginx that supports nodejs?

**Comment by macolo** [comment]
Solved via https://blog.typodrive.com/2020/07/31/deploy-a-production-ready-react-app-on-divio-com-http-to-https-redirect-on-nginx/
