### ISSUE TITLE
divio platform returns 502 and 408 errors few times in 10 days (not related to deployments), only one project affected, hosted at AZ region

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#31]
Hi @GaretJax, I got a client request from the project https://control.divio.com/control/6276/edit/82867/, which implied that the server didn't process a third-party callback (the successful payment callback).

I didn't get a sentry error, but I remembered there's an external cronjob that runs every minute to ping a specific url - yes, "the good old way" :) - and every other 10 days it fails. Before I thought that it was due to a timeout on the cronjob side, but today I found out that the cronjob ignores the timeout, and actually runs into 502 and 408 errors.

That cronjob used to work normally before the migration to divio from AWS. Here's the times when the cronjob failed with the error codes (with UTC time):
```
502 - Tue, Jun 23, 11:11 PM
408 - Tue, Jun 30, 07:06 AM
408 - Sun, Jul 5,  01:06 PM
408 - Sun, Jul 5,  11:06 PM
408 - Tue, Jul 7,  01:06 PM
408 - Fri, Jul 10, 05:06 AM
408 - Wed, Jul 15, 11:06 PM
502 - Fri, Jul 17, 07:11 PM
408 - Wed, Jul 22, 11:06 AM
502 - Wed, Jul 29, 11:06 AM
408 - Fri, Aug 7,  05:09 PM
502 - Tue, Aug 18, 12:43 AM
502 - Tue, Aug 18, 12:44 AM
502 - Tue, Aug 18, 12:45 AM
502 - Tue, Aug 18, 12:46 AM
502 - Tue, Aug 18, 12:47 AM
502 - Tue, Aug 18, 12:48 AM
```

Would you be able to help with this one? Since this project has a payment system missing the callbacks isn't really an option 😅

**Comment by macolo** [comment]
hi @victor-yunenko is this still happening?

**Comment by viktor-yunenko** [comment]
No, it stopped happening after we adjusted the load balancer config with Jonathan - you can see that we don't get jenkins downtime alerts anymore ✔️

Looks like we can close this one.
