### ISSUE TITLE
Divio Control shows error message: The commits on the 'master' branch differ between the current and the new repository! Please bring the branches in sync to change the repository when copying a project

### ISSUE THREAD

**Issue by macolo** [what-digital/divio#35]
## Context

- fork copies the code of the original's project's repo into a new git repo on divio (even if original project has external git repo configured)
- mirror doesnt have its own git, uses the upstream project's one (branches can still be configured freely for the mirror's environments)
- copy creates it's own blank git repo on divio (even if original project has external git repo configured) and divio bot adds the initial commits (as when creating a new project). Only divio control settings such as env variables are copied over.

More info here: https://support.divio.com/how-to/duplicate-project/

## Workarounds / Solutions
1. create a fork (instead of a copy)
2. configure external git repo (no warnings should show up)

## Problem statement
- if a project in divio control is copied, a configured external git repository is not copied over.
- when migrating from a divio git to an external git repo (i.e. gitlab) this message pops up even for duplicated projects
- in general it impedes a straighforward duplication of a project, because we have to find out the divio git url somehow and then force push our external repository's content to the divio git repo first. 
- There should be an option to override this warning in the Divio UI on this screen: 

![image](https://user-images.githubusercontent.com/4056979/98359573-c1f87b80-2028-11eb-850a-c702f418be70.png)

**Comment by macolo** [comment]
cc @victor-yunenko @GaretJax

**Comment by macolo** [comment]
Note: Divio tech team is working on phasing out the current "copy" option and renaming "fork" option to "copy" or "duplicate".

**Comment by kinkerl** [comment]
the "copy" function is removed with the next update. do we have something left to work on?
