### ISSUE TITLE
After the latest interface upgrade it isn't possible to copy data from live to stage on mirror projects

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#4]
![image](https://user-images.githubusercontent.com/36416236/85303830-b0686a00-b4b3-11ea-90c3-aaf498a331df.png)

Of course it's possible using divio-cli, but not everybody can manage that :)

**Comment by vxsx** [comment]
Thanks for the report! I'm currently working on restoring this functionality in the UI.

**Comment by vxsx** [comment]
The fix was deployed last week for this.

**Comment by viktor-yunenko** [comment]
Thank you, I can see on the mirror projects now 🙏
