### ISSUE TITLE
SSH tunneling to access stage database from localhost doesn't appear to be working (Use case: debugging and fixing live dbs)

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#40]
Eg psql command doesn't work.

**Comment by macolo** [comment]
This is by design, due to security concerns it's not possible to directly connect to the database from outside.

Please also see https://docs.divio.com/en/latest/how-to/interact-database/#interact-with-the-cloud-database

**Comment by macolo** [comment]
Also, SSH tunneling via the SSH instructions should work, like this: https://support.divio.com/en/articles/735276-how-to-ssh-into-your-cloud-server

**Comment by macolo** [comment]
hi @victor-yunenko if you are happy with my answers please feel free to close otherwise please specify

**Comment by viktor-yunenko** [comment]
> Also, SSH tunneling via the SSH instructions should work, like this: https://support.divio.com/en/articles/735276-how-to-ssh-into-your-cloud-server

Did the ssh tunnel work for you? I was receiving an error when I tried last time

**Comment by viktor-yunenko** [comment]
A whitelist is a good practice, but I would say the problem here is the inability to configure or workaround it. Ie it isn't possible to simulate a server instance anymore then.

**Comment by macolo** [comment]
@victor-yunenko it would be great if you could share the CLI command you used to set up the SSH tunnel here (without the project's credentials), thank you!

**Comment by macolo** [comment]
Note: 

Use cases: 
- sometimes on a production server a bug must be resolved by changing db data. live server db cannot / must not be pulled, fixed and pushed, developers would like to use local database UI's and need tunneling for that into the live db.
- manage content in a CMS from local dev env together with other devs on their own local dev envs.

**Comment by macolo** [comment]
Alternative to use case: use fixtures

**Comment by viktor-yunenko** [comment]
I tried ssh tunneling lately, that seems to work fine. I would say it deserves documentation since on other platforms a user usually gets the ability to configure the whitelisting.

**Comment by viktor-yunenko** [comment]
We aren't affected by it at the moment, hence we'll close it for now.
