### ISSUE TITLE
port 25 is blocked on new AWS accounts contrary to divio documentation

### ISSUE THREAD

**Issue by macolo** [what-digital/divio#42]
- Port 25 doesnt work on AWS: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/
- divio.com documentation should mention this at least but it would be better if divio docs would switch the default port away from port 25 and update its documentation: https://docs.divio.com/en/latest/reference/coding-sending-email/
- this appears to be an AWS account-level setting. It's probably already correctly set on the public cloud of divio.com, but in any private clouds (= separate AWS accounts) it doesnt work.

**Comment by macolo** [comment]
cc @GaretJax

**Comment by macolo** [comment]
> - this appears to be an AWS account-level setting. It's probably already correctly set on the public cloud of divio.com, but in any private clouds it doesnt work. 

I have updated the issue description with additional information.

**Comment by macolo** [comment]
Update from divio:
> Apparently we can lift the block only on single EC2 instances, but we regularly cycle them, so new ones would be blocked again. We can try to investigate with their support if this is feasible, but I don't think so.

AWS requires a written request from us:
> If you would like us to proceed that way, please provide the following: A clear and detailed use case for sending email from your EC2 instance or NAT Gateway. A statement outlining your plan for assuring that your account isn't implicated in sending unwanted emails.
>

divios recommendation:
> I guess you're using a third party service (SMTP relay) to send emails, rather than directly delivering it to recipients. If the service itself does not provide an alternative port (e.g. mailgun does), then it should at least provide one of the encrypted alternatives (which would be better to use anyway), such as 465, or 587 (see https://www.mailgun.com/blog/which-smtp-port-understanding-ports-25-465-587/).

**Comment by macolo** [comment]
@evildmp I guess it would still be good to document this so that next time this happens nobody needs to invest debugging time.

**Comment by evildmp** [comment]
Updated in https://docs.divio.com/en/latest/reference/coding-sending-email/.
