### ISSUE TITLE
setting DOMAIN_REDIRECTS in the divio env vars in divio control resets the domain redirect settings in divio control

### ISSUE THREAD

**Issue by macolo** [what-digital/divio#44]
- set DOMAIN_REDIRECTS in the divio control env vars (we use it to redirect the aldryn.io technical project domain to the real domain (like domain.com) due to SEO reasons (duplicate content!)
- This leads to undesired behaviour: setting the env vars will override any settings made in the divio control domain section such as in the screenshot below
- the desired behaviour is that the domain redirect settings in divio control still works even after setting DOMAIN_REDIRECTS in the divio control env vars.
- workaround: you must add all the domains you want to redirect to DOMAIN_REDIRECTS (separated by semi-colon, no spaces) even if you have divio control domain redirects configured.

Here is depicted how the env var is set:

![image](https://user-images.githubusercontent.com/4056979/112304086-5cd2b900-8c9d-11eb-8135-c32c42a3d9f3.png)

the following configuration will NOT redirect apgsga.ch to www.apgsga.ch if DOMAIN_REDIRECTS is set to `apg-website-2021-private-cloud.apg.divio.cloud` only. The workaround is to set `DOMAIN_REDIRECTS` to `apgsga.ch,apg-website-2021-private-cloud.apg.divio.cloud`

![image](https://user-images.githubusercontent.com/4056979/112304213-855ab300-8c9d-11eb-81fb-82166efda244.png)

**Comment by evildmp** [comment]
This is already documented in https://docs.divio.com/en/latest/reference/addons-aldryn-django/#domain-redirects, but I will make it clearer.

**Comment by evildmp** [comment]
Done.
