### ISSUE TITLE
Release command labels should be unique (input validation missing)

### ISSUE THREAD

**Issue by macolo** [what-digital/divio#52]
- Release command labels should be unique (input validation missing)
- Currently it's possible to add the same label (i.e. `Default`) multiple times which causes the Command input fields to reset.

![image](https://user-images.githubusercontent.com/4056979/129457005-7769792f-1b0f-4ba9-b651-8ddeb84756ae.png)

**Comment by macolo** [comment]
cc @kinkerl

**Comment by kinkerl** [comment]
valid point. internal ticket created for planning

**Comment by kinkerl** [comment]
@macolo this is resolved now. validation is implemented und released
