### ISSUE TITLE
divio bot changes Dockerfile in commit "configure baseproject debian 8.7" (it shouldnt)

### ISSUE THREAD

**Issue by macolo** [what-digital/divio#59]
- Commit by divio bot: configure baseproject debian 8.7
- It doesn't do anything visible, just deletes all lines of Dockerfile and adds them back. Probably some issue with different line breaks?
- this happens whenever a project is created (gitlab repository is added), or a new environment is created, or a branch is changed on an existing environment

![image](https://user-images.githubusercontent.com/4056979/157643728-a721b57e-3d41-4a6e-8250-68c7b9fc228b.png)

![image](https://user-images.githubusercontent.com/4056979/157644067-c027dfc7-3c8c-4bc5-9277-a328918e47ac.png)

**Comment by macolo** [comment]
cc @GaretJax

**Comment by macolo** [comment]
update from Divio team:
> We changed some internal logic so the .gitignore file is not longer required and it got removed.
We have a change in the pipeline so webhooks triggers will not push any changes back and will just "blindly" accept the changes from the origin. This should solve the force push issue.

**Comment by kinkerl** [comment]
We updated the logic and this situation should not happen anymore
