### ISSUE TITLE
divio has a "secret" `reset to origin` button in the repository settings

### ISSUE THREAD

**Issue by viktor-yunenko** [what-digital/divio#6]
It's relatively easy to break a project without knowing about this button.

![image](https://user-images.githubusercontent.com/36416236/85316365-4f499200-b4c5-11ea-91bc-20fd2258e335.png)

Unless the user knows about it often the only way to fix a project is to create a copy with another slug. We had to resort to that on 4 projects before one of the developers found this button while clicking on anything without a purpose. Before that nobody knew that divio keeps its own repository and I guess when it fails to resolve a merge conflict it starts yielding a generic error, most often I saw something as `ensure that you have a master branch with a readme` :)

We also noticed that divio somehow keeps the internal repository even when we delete a project completely and then create a project with the same slug. Thus we needed to create projects with different slugs :)

This button is important and should be visible to the user. Also an actual error message and documentation of how divio does handles the internal repository would help. Perhaps linked directly within the Repository CP section?

**Comment by kinkerl** [comment]
We will check the documentation and the error message. We have a (very) brief explanation here http://support.divio.com/en/articles/2851301-remote-git-reset-to-origin but its probably not elaborate enough.

**Comment by viktor-yunenko** [comment]
Thank you :)

Btw here's the error that I meant, one developer just run into it:

![image](https://user-images.githubusercontent.com/36416236/86227571-e1245f80-bb95-11ea-888a-f7437f03a22b.png)

**Comment by macolo** [comment]
Divio will change this behaviour in Q2 20201 - explanations and workarounds are available here: https://github.com/what-digital/divio/issues/35 and #37
